# Site settings
title: Haverford Robotics Lab
lab_name: Haverford Robotics Lab
author: >
  Professor Thao Nguyen and the Haverford Robotics Lab
institution: Haverford College
email: contact@haverford.edu
description: >
  The Haverford Robotics Lab, led by Professor Thao Nguyen, performs cutting-edge robotics research.
baseurl: ""
url: ""
twitter_username: 
github_username: 
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
